Update base directory name for beta sdk
microsoftgraph/MSGraph-SDK-Code-Generator pull request #1085
Opened 2023-10-31 11:19 UTC by samwelkanda

## Summary

Give a description of what your pull request does and what platform[s] it targets. Use the *breaking changes* tag if applicable. Breaking changes can include changes to generated code files which will impact API signature or behaviors, and changes to directory structures which may impact DevOp pipelines and scripts.

## Generated code differences

Pull requests that result in changes to generated code and/or directory structures should include example diffs of the resulting changes. This makes code review much easier.

## Command line arguments to run these changes

Provide the command line arguments here so that reviewers can quickly repro the results of changes.

## Links to issues or work items this PR addresses

2023-10-31 12:24 UTC, baywet requested changes

2023-10-31 12:24 UTC, baywet commented on .azure-pipelines/generation-templates/python-beta.yml
> +    RepoModelsDir: '$(Build.SourcesDirectory)/${{ parameters.repoName }}/msgraph_beta/generated'
my understanding is that we duplicated the file just for the msgraph_beta segment here (x2), could we not instead add an additional parameter to original template?

2023-11-01 07:49 UTC, andrueastman approved these changes

2023-11-01 10:15 UTC, baywet approved these changes
Thanks for making the changes

2023-11-01 14:12 UTC, merged