Remove increment minor version script
microsoftgraph/MSGraph-SDK-Code-Generator pull request #1227
Opened 2024-05-16 07:47 UTC by Ndiritu

part of https://github.com/microsoftgraph/msgraph-beta-sdk-java/issues/940

2024-05-16 08:10 UTC, andrueastman approved these changes

2024-05-16 12:06 UTC, baywet requested changes
I believe you need to replicate the change in #1212 for everything to work end to end here

2024-05-20 09:18 UTC, andrueastman approved these changes

2024-05-20 10:55 UTC, baywet approved these changes

2024-05-20 10:55 UTC, merged