Remove IGraphServiceClient interface and add TokenCredential constructor
microsoftgraph/MSGraph-SDK-Code-Generator pull request #477
Opened 2021-03-10 12:06 UTC by andrueastman

This PR:
- Closes https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/462
- Closes https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/461

2021-03-10 12:59 UTC, baywet requested changes
A mapping for the IEntityClient in the config probably needs to be removed as well. Also this https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/pull/244#discussion_r591473350

2021-03-11 08:04 UTC, andrueastman commented on Templates/templates/CSharp/Requests/EntityClient.cs.tt
> +        /// <param name="scopes">Scopes required to access Microsoft Graph. This defaults to https://graph.microsoft.com/.default when none is set.</param>
XML Comment

2021-03-11 08:05 UTC, andrueastman commented
Thanks for the tip @baywet. I have resolved the config issue.
With regards to the AuthProvider, there is no need to do a null check. The Auth provider will set the scopes to be a default value if not provided therefore no need to throw. See [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/bcbc09cbe9b5e4be80f3a39acbd1cd5361257a81/src/Microsoft.Graph.Core/Authentication/TokenCredentialAuthProvider.cs#L36).
Furthermore, the XML comments of the constructor captures [this](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/477/files#r592140591) and explains as well.

2021-03-11 11:08 UTC, baywet approved these changes

2021-03-11 14:11 UTC, merged