Fix the setting of odata.type in the constructor
microsoftgraph/MSGraph-SDK-Code-Generator pull request #534
Opened 2021-05-24 05:46 UTC by andrueastman

## Summary
This PR closes https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/242

2021-05-25 18:26 UTC, baywet requested changes

2021-05-25 18:26 UTC, baywet commented on Templates/templates/CSharp/Model/ComplexType.cs.tt
> +        else if (isBaseTypeReferenced)
```suggestion
        if (!complex.IsAbstract && isBaseTypeReferenced)
```
And remove the block above

2021-05-25 18:26 UTC, baywet commented on Templates/templates/CSharp/Model/EntityType.cs.tt
> +    <#
```suggestion
<#
```

2021-05-25 18:26 UTC, baywet commented on src/GraphODataTemplateWriter/Extensions/OdcmModelExtensions.cs
> +                                  && param.Type.Name != "entity"));
```suggestion
                                  && "entity".Equals(param.Type.Name, StringComparison.OrdinalIgnoreCase)));
```
protects you from casing differences and the name being null

2021-05-25 18:26 UTC, baywet commented on src/GraphODataTemplateWriter/Extensions/OdcmModelExtensions.cs
> +                    .Select(someType => someType)
```suggestion
```

2021-05-25 18:26 UTC, baywet commented on src/GraphODataTemplateWriter/Extensions/OdcmModelExtensions.cs
> +                    .Where(someType => someType is OdcmClass)
```suggestion
                    .OfType<OdcmClass>()
```

2021-05-25 18:26 UTC, baywet commented on src/GraphODataTemplateWriter/Extensions/OdcmModelExtensions.cs
> +                    .Any(someType => ((OdcmClass) someType).Properties
```suggestion
                    .Any(someType => someType.Properties
```

2021-05-26 08:01 UTC, andrueastman commented on src/GraphODataTemplateWriter/Extensions/OdcmModelExtensions.cs
> +                    .Any(someType => ((OdcmClass) someType).Properties
Resolved via https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/534/commits/5078472debf1e32df30f74a5aa4db8ff0b8106a6

2021-05-26 08:02 UTC, andrueastman commented on Templates/templates/CSharp/Model/EntityType.cs.tt
> +    <#
Resolved via https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/534/commits/5078472debf1e32df30f74a5aa4db8ff0b8106a6

2021-05-26 08:03 UTC, andrueastman commented
Thanks for the great feedback @baywet. I have updated the PR with the feedback changes.

2021-05-26 11:29 UTC, baywet approved these changes

2021-05-26 13:57 UTC, merged